server:
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 300
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 1
 
# 日志配置
logging:
  config: classpath:logback-spring.xml
  file: /data/log/${spring.profiles.active}/${project.name}_${spring.profiles.active}.log
  file.max-size: 50MB
  #当参数定义int简单类型并使用@apiModelPerperty标签时,如果不指名example属性,会导致swagger类型转换错误,信息如下
  #java.lang.NumberFormatException: For input string: ""
  level.io.swagger.models.parameters.AbstractSerializableParameter: error

# Mysql Redis RocketMQ
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

app:
  filter:
    # 拦截器开关
    enable: true
    # 加密key和向量
    aes:
      localIV: 1120012735479907
      localKey: 18d0647fa7b47b51
    # 最优服务器
    bestServerUrl: /system/server/getBestServerAction
    # 设备映射
    device:
      android:
        code: 2
        value: ride-app-android-001
      ios:
        code: 3
        value: ride-app-ios-001
    # 忽略登录
    notNeedLogin:
      urls: /home/overview,/register/submit,/register/notice,/user/login,/smscode/send,/smscode/check,/user/password/reset,/system/server/getBestServerAction,/building/list,/building/info,/building/cityList,/buildingParking/transferList,/buildingParking/transferInfo,/appVersion/versionCheck

datasource:
 #从库数量
  readSize: 1
   # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  # 事务和数据源切换切面
  aop:
    scan: execution(* com.personal.ride..*Service.*(..))
#主库
  write:
    url: jdbc:p6spy:mysql://localhost:3306/ride?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: cwjy_dev
    password: ZHXaW3@xIK
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: -1
  read:
    url: jdbc:p6spy:mysql://localhost:3306/ride?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: cwjy_dev
    password: ZHXaW3@xIK
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: -1


# Redis
redis:
  ip: 39.98.147.151
  port: 6666
  pool:
    maxActive:  1024
    maxIdle: 200
    maxWait: 10000
    testOnBorrow: true
    testOnReturn: true
    password: Asds36Cs9HBF

swagger:
  enabled: true
  title: cr-app
  description: Starter for swagger 2.x
  version: 1.0.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  contact.name: framework
  base-package: com.chuangrong.app.controller
  base-path: /**
  exclude-path: /error, /ops/**
  globalOperationParameters[0]:
    name: token
    description: token
    modelRef: string
    parameterType: header
    required: true

# ******************* 以下放业务参数配置  **********************
ride:
  best:
    host: http://localhost:8072/app
  #支付模块请求链接
  pay:
    url: http://localhost:8073/cr-pay